client/src/components/gameShared/ResponseList.vue
client/src/components/lobby/Lobby.vue
client/src/components/promptResponse/PromptResponse.vue
client/src/components/selection/ActiveSelection.vue
client/src/components/selection/PassiveSelection.vue
client/src/components/selection/SelectionType.vue
client/src/locales/en.json
client/src/store/modules/game.js
client/src/views/Game.vue
server/models/gameState.js
server/models/rooms.js
server/routes/socketio/gameHandlers.js
server/tests/routes/promptResponse.js
server/tests/routes/responseSelection.js

- add an active selection and passive selection page
- add backend to accept selection from correct selector
- add backend to handle state machine of rotating selections
- add unit tests to test backend

Selection page

---

.idea/jsLibraryMappings.xml
.idea/runConfigurations/client.xml
.idea/runConfigurations/server_tests.xml
.idea/watcherTasks.xml
client/.browserslistrc
client/package-lock.json
client/package.json
client/postcss.config.js
client/src/App.vue
client/src/main.js
client/src/styles/_min-bootstrap.scss
client/src/styles/_variables.scss
client/src/styles/app.scss
client/vite.config.js

- import custom bootstrap instead of prestyled bootstrap
- customize some bootstrap variables
- include autoprefixer to auto prefix bootstrap css
- setup purgecss for production to reduce css file size

- add scss loader to project

---

.github/workflows/automated_git_config.yml
.idea/runConfigurations/server_tests.xml
server/package.json
server/tests/models/autoMatch.js
server/tests/routes/createjoin.js

Finished setting up CI pipeline

Setup automated git testing

---

client/src/locales/en.json
client/src/views/Game.vue
client/src/views/Home.vue
server/bin/www
server/models/rooms.js
server/routes/socketio/roomHandlers.js
server/routes/socketio/roomService.js

* Small simple PR that checks for rooms that have been inactive for longer than 10 minutes and closes that room

Inactivity kick

---

client/src/components/promptResponse/PromptResponse.vue
client/src/components/promptResponse/VoteSkip.vue
client/src/components/responseSelection/SelectionType.vue
client/src/locales/en.json
client/src/store/modules/game.js
server/models/gameState.js
server/routes/socketio/gameHandlers.js
server/tests/models/autoMatch.js
server/tests/models/completeCallbacks.js
server/tests/models/voteSkipPrompt.js
server/tests/routes/promptResponse.js

* optional vote skip prompt
* Bad frontend UI that supports it
* Tests

Vote skip prompt

---

client/src/App.vue
client/src/components/lobby/Lobby.vue
client/src/components/lobby/PlayerCard.vue
client/src/components/lobby/PlayerList.vue
client/src/locales/en.json
client/src/styles/_variables.scss
client/src/styles/app.scss

Style lobby

---

client/src/views/Home.vue
server/models/rooms.js
server/package-lock.json
server/package.json
server/routes/socketio/roomHandlers.js
server/tests/resources/prompts/en/pack1.txt
server/tests/resources/prompts/en/pack2.txt
server/tests/resources/prompts/en/pack3.txt
server/tests/resources/prompts/fr/pack1.txt
server/tests/resources/prompts/fr/pack2.txt
server/tests/resources/prompts/fr/pack3.txt
server/tests/routes/createjoin.js

* use parameterize to properly handle room names

Localize roomNames

---

server/models/misspellMatch.js
server/tests/models/autoMatch.js

Bug: false positive matches occuring due to auto correct

---

server/models/misspellMatch.js
server/tests/models/autoMatch.js

* add case-insensitivity to misspelled matching
* add tests

case-insensitive misspell matching

---

client/src/store/modules/game.js
server/models/gameState.js
server/models/rooms.js
server/routes/socketio/gameHandlers.js
server/routes/socketio/roomHandlers.js
server/tests/models/sikeDispute.js

* add midgame reconnect
* add midgame join

Midgame Join

---

client/src/components/gameShared/ResponseList.vue
client/src/components/gameShared/SelectionType.vue
client/src/components/gameShared/Timer.vue
client/src/components/lobby/Lobby.vue
client/src/components/lobby/PlayerList.vue
client/src/components/responseMatching/ActiveMatching.vue
client/src/components/responseMatching/MatchingSummary.vue
client/src/components/responseSelection/Selection.vue
client/src/components/responseSelection/SelectionPicker.vue
client/src/locales/en.json
client/src/store/modules/game.js
client/src/styles/app.scss
client/src/views/Game.vue

* added selectionType to all pages to be clearer
* added sound effects for notifications
* added cursor effect

Small updates to make interface clearer

---

server/models/gameState.js
server/models/matchUtils.js
server/models/rooms.js
server/package-lock.json
server/package.json
server/routes/socketio/roomHandlers.js
server/tests/models/autoMatch.js

* add pluralize library to improve auto matching

Pluralization

---

client/package-lock.json
client/package.json
client/src/App.vue
client/src/components/countdown/Countdown.vue
client/src/components/endGame/EndGame.vue
client/src/components/endRound/EndRound.vue
client/src/components/gameShared/Prompt.vue
client/src/components/gameShared/ResponseList.vue
client/src/components/gameShared/Timer.vue
client/src/components/lobby/Lobby.vue
client/src/components/promptResponse/PromptResponse.vue
client/src/components/promptResponse/VoteSkip.vue
client/src/components/responseMatching/ActiveMatching.vue
client/src/components/responseMatching/MatchCard.vue
client/src/components/responseMatching/MatchingSummary.vue
client/src/components/responseSelection/Selection.vue
client/src/locales/en.json
client/src/store/modules/game.js
client/src/styles/_min-bootstrap.scss
client/src/styles/app.scss
client/src/views/Game.vue
client/vite.config.js
server/models/gameState.js

* fix lots of small visual bugs
* improve intuitiveness of UI
* improve UI for mobile
* fix reconnect bug

Visual bug updates

---

client/package.json
client/postcss.config.js
client/src/components/lobby/Options.vue
client/src/components/promptResponse/VoteSkip.vue
client/src/components/responseMatching/ActiveMatching.vue
client/src/components/responseMatching/DisputeIcon.vue
client/src/components/responseMatching/MatchingSummary.vue
client/src/locales/en.json
client/src/main.js
client/src/store/modules/game.js
client/src/styles/app.scss
server/bin/www
server/models/gameState.js
server/models/optionsSchema.js
server/models/pollService.js
server/models/rooms.js
server/routes/socketio/gameHandlers.js
server/routes/socketio/roomService.js
server/tests/models/completeCallbacks.js
server/tests/models/voteSkipPrompt.js

* add UI for sike dispute
* add option in options menu for sike dispute
* fix small display bug with bootstrap and purgecss

73 make sike dispute an optional part of matching instead of its own section

---

client/src/components/endGame/EndGame.vue
client/src/components/responseMatching/ActiveMatching.vue
client/src/locales/en.js
server/models/gameState.js

Small fixes

---

client/src/components/endGame/EndGame.vue

126 fix player rank when there are ties

---

client/src/components/gameShared/ResponseList.vue
client/src/store/modules/game.js

* note did not add recovery for midgame rejoin, as this will be addressed when the response infrastructure is changed to allow viewing of other peoples responses

add the colouring requested

---

client/src/components/gameShared/VolumeControl.vue

* make it 1 press mute
* hover for slider
* reduce disappear time for slider

Update volume slider

---

client/src/locales/en.ts
client/src/views/About.vue
client/src/views/HowToPlay.vue

- Added buttons to the bottom of the home and about pages

155 add navigation buttons to about and how to play

---

client/.eslintrc.cjs
client/src/App.vue
client/src/components/responseMatching/ActiveMatching.vue
client/src/locales/index.ts
client/src/stores/game.ts
client/src/stores/room.ts
client/src/stores/settings.ts
client/src/views/About.vue
client/src/views/HowToPlay.vue
common/src/socketioTypes.ts
common/src/stateTypes.ts
server/src/routes/gameHandlers.ts
server/src/state/gameState.ts
server/src/state/pollService.ts

Each bullet has it's own commit so check each commit
* Fix HMR
* replace div in button with span
* Update client vote count when client disconnects

 Minor Fixes
